[package]
name = "bd-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bd-core.workspace = true
crossbeam-channel.workspace = true
quinn.workspace = true
rustls.workspace = true
rcgen.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
